<?php
/**
 * Страница "Содержание".
 * 
 * Английская (британская) локализация.
 * 
 * Этот файл является частью модуля веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>Site materials</h1>
    <div class="g-help-icon">
        <img src="<?= $assetsUrl, '/images/icon.svg' ?>" />
    </div>
    <p>Site materials are site articles with appropriate presentation of information. Each material determines the type of information display on the site page.</p>

    <h2>Contents:</h2>
    <ul class="g-help-list">
        <li><a href="<?= $url('desk') ?>">Materials desk</a></li>
        <li><a href="<?= $url('grid') ?>">List of site materials</a></li>
        <li><a href="<?= $url('form') ?>">Site material editing form</a></li>
    </ul>
</article>